services:
  - type: web
    name: dwg-analyzer
    env: python
    plan: free
    buildCommand: "cp pyproject_render.toml pyproject.toml && poetry install"
    startCommand: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
    envVars:
      - key: DATABASE_URL
        value: postgresql://yang:nNTm6Q4un1aF25fmVvl7YqSzWffyznIe@dpg-d0t3rlili9vc739k84gg-a.oregon-postgres.render.com/dg4u_tiktok_bot
      - key: PYTHON_VERSION
        value: "3.12.0"